filebeat.inputs:
 - type: log
   paths:
    - /var/log/serverlogs/*.log
filebeat.modules:
 - module: nginx
   access:
    enabled: true
    var.paths: ["/custom/path/to/logs"]
   error:
    enabled: true
    var.paths: ["/custom/path/to/logs"]
filebeat.config.modules:
   path: ${path.config}/modules.d/*.yml
   reload.enabled: true

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
#setup.dashboards.enabled: true
#setup.kibana.host: "http://localhost:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: 'filebeat-%{[beat.version]}-%{+yyyy.MM.dd}'

