filebeat.inputs:
- type: log
  paths:
    - /usr/log/serverlogs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  hosts: '${KIBANA_HOSTS:kibana:5601}'
  username: elastic
  password: changeme%

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
